### ISSUE TITLE
Feature: Broadcast messages

### ISSUE THREAD

**Issue by yvdjee** [antonmyronyuk/aioviberbot#6]
It would be nice if the broadcast messages is supported.
https://developers.viber.com/docs/api/rest-bot-api/#broadcast-message

**Comment by antonmyronyuk** [comment]
Hi, thanks for suggestion! I will consider implementing message broadcasting in nearest weeks.

**Comment by antonmyronyuk** [comment]
Hi, @yvdjee

Message broadcasting is already available in version `0.3.0` 
https://pypi.org/project/aioviberbot/0.3.0/
